# Generated by Django 5.2 on 2025-05-05 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=40)),
                ('created_at', models.DateField()),
                ('difficulty', models.CharField()),
                ('category', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('background', models.CharField()),
                ('card_path', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front', models.CharField(max_length=20)),
                ('back', models.CharField(max_length=30)),
                ('difficulty', models.CharField()),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flipquestapi.deck')),
            ],
        ),
        migrations.CreateModel(
            name='Flipper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15)),
                ('coins', models.IntegerField(blank=0, null=0)),
                ('created_at', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('theme', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='flipquestapi.theme')),
            ],
        ),
        migrations.AddField(
            model_name='deck',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='flipquestapi.flipper'),
        ),
        migrations.CreateModel(
            name='Likeddeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_at', models.DateField()),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flipquestapi.deck')),
                ('flipper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flipquestapi.flipper')),
            ],
        ),
    ]
